services:
  minio:
    image: minio/minio:latest
    ports:
      - "9222:9000"
      - "9211:9211"   # MinIO Console
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9211"
    volumes:
      - minio_data:/data

volumes:
  minio_data: